# Generated by Django 5.2.1 on 2025-05-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_uploadedfile_file_type_uploadedfile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'name')},
        ),
    ]
